In [1]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv')

In [34]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,4,10,10,10
366,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,13,13,13
367,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,7,6,0
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
369,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,10,14,12,11
370,MS,F,19,U,LE3,T,3,2,services,services,...,3,2,2,1,1,3,4,7,7,9
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
374,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,19,18,19
375,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,2,8,8,10
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
377,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,4,8,9,10
378,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,0,15,15,15
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,15,14,14
381,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,5,7,6,7
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
383,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,6,5,0
384,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,14,6,5,5
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,7,6,5,6
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,7,5,0
388,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,0,7,9,8
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [35]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

# step4

In [36]:
df2 = df.loc[:,'school':'guardian']

In [37]:
df2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father
12,GP,M,15,U,LE3,T,4,4,health,services,course,father
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother
14,GP,M,15,U,GT3,A,2,2,other,other,home,other
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother
19,GP,M,16,U,LE3,T,4,3,health,other,home,father
20,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother
21,GP,M,15,U,GT3,T,4,4,health,health,other,father
22,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother
23,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother
24,GP,F,15,R,GT3,T,2,4,services,health,course,mother
25,GP,F,16,U,GT3,T,2,2,services,services,home,mother
26,GP,M,15,U,GT3,T,2,2,other,other,home,mother
27,GP,M,15,U,GT3,T,4,2,health,services,other,mother
28,GP,M,16,U,LE3,A,3,4,services,other,home,mother
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother
...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother
366,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother
367,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother
368,MS,F,18,U,GT3,T,2,3,at_home,services,course,father
369,MS,F,18,R,GT3,T,4,4,other,teacher,other,father
370,MS,F,19,U,LE3,T,3,2,services,services,home,other
371,MS,M,18,R,LE3,T,1,2,at_home,services,other,father
372,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother
373,MS,F,17,R,GT3,T,1,2,other,other,course,mother
374,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother
375,MS,F,18,R,GT3,T,1,1,other,other,home,mother
376,MS,F,20,U,GT3,T,4,2,health,other,course,other
377,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother
378,MS,F,18,U,GT3,T,3,3,other,other,home,mother
379,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father
381,MS,M,18,R,GT3,T,2,1,other,other,other,mother
382,MS,M,17,U,GT3,T,2,3,other,services,home,father
383,MS,M,19,R,GT3,T,1,1,other,services,other,mother
384,MS,M,18,R,GT3,T,4,2,other,other,home,father
385,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother
387,MS,F,19,R,GT3,T,2,3,services,other,course,mother
388,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother
389,MS,F,18,U,GT3,T,1,1,other,other,course,mother
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

#  step5

In [40]:
capi = lambda x:x.capitalize()

# step6

In [43]:
df2['Fjob'].apply(capi)

0       Teacher
1         Other
2         Other
3      Services
4         Other
5         Other
6         Other
7       Teacher
8         Other
9         Other
10       Health
11        Other
12     Services
13        Other
14        Other
15        Other
16     Services
17        Other
18     Services
19        Other
20        Other
21       Health
22        Other
23        Other
24       Health
25     Services
26        Other
27     Services
28        Other
29      Teacher
         ...
365       Other
366    Services
367    Services
368    Services
369     Teacher
370    Services
371    Services
372     At_home
373       Other
374       Other
375       Other
376       Other
377    Services
378       Other
379       Other
380     Teacher
381       Other
382    Services
383    Services
384       Other
385       Other
386     At_home
387       Other
388    Services
389       Other
390    Services
391    Services
392       Other
393       Other
394     At_home
Name: Fjob, Length: 395, dtype: object

In [42]:
df2['Mjob'].apply(capi)

0       At_home
1       At_home
2       At_home
3        Health
4         Other
5      Services
6         Other
7         Other
8      Services
9         Other
10      Teacher
11     Services
12       Health
13      Teacher
14        Other
15       Health
16     Services
17        Other
18     Services
19       Health
20      Teacher
21       Health
22      Teacher
23        Other
24     Services
25     Services
26        Other
27       Health
28     Services
29      Teacher
         ...
365     At_home
366     Teacher
367       Other
368     At_home
369       Other
370    Services
371     At_home
372       Other
373       Other
374       Other
375       Other
376      Health
377     Teacher
378       Other
379     At_home
380     Teacher
381       Other
382       Other
383       Other
384       Other
385     At_home
386     Teacher
387    Services
388     Teacher
389       Other
390    Services
391    Services
392       Other
393    Services
394       Other
Name: Mjob, Length: 395, dtype: object

# step7

In [46]:
df.shape

(395, 33)

In [81]:
df.tail(1).iloc[0][32]

9

In [79]:
df.tail(1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [88]:
df.iloc[len(df.index)-1,len(df.columns)-1]

9

# step8

In [94]:
df['Mjob'] = df['Mjob'].str.upper()

# step 9

In [106]:
def majority(x):
    if x>7:
        return True
    else:
        return False

In [107]:
df['legal'] = df['age'].apply(majority)

In [103]:
df['ss'] = df['age']>15

In [108]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,ss,legal
0,GP,F,18,U,GT3,A,4,4,AT_HOME,teacher,...,4,1,1,3,6,5,6,6,True,True
1,GP,F,17,U,GT3,T,1,1,AT_HOME,other,...,3,1,1,3,4,5,5,6,True,True
2,GP,F,15,U,LE3,T,1,1,AT_HOME,other,...,2,2,3,3,10,7,8,10,False,True
3,GP,F,15,U,GT3,T,4,2,HEALTH,services,...,2,1,1,5,2,15,14,15,False,True
4,GP,F,16,U,GT3,T,3,3,OTHER,other,...,2,1,2,5,4,6,10,10,True,True
5,GP,M,16,U,LE3,T,4,3,SERVICES,other,...,2,1,2,5,10,15,15,15,True,True
6,GP,M,16,U,LE3,T,2,2,OTHER,other,...,4,1,1,3,0,12,12,11,True,True
7,GP,F,17,U,GT3,A,4,4,OTHER,teacher,...,4,1,1,1,6,6,5,6,True,True
8,GP,M,15,U,LE3,A,3,2,SERVICES,other,...,2,1,1,1,0,16,18,19,False,True
9,GP,M,15,U,GT3,T,3,4,OTHER,other,...,1,1,1,5,0,14,15,15,False,True
10,GP,F,15,U,GT3,T,4,4,TEACHER,health,...,3,1,2,2,0,10,8,9,False,True
11,GP,F,15,U,GT3,T,2,1,SERVICES,other,...,2,1,1,4,4,10,12,12,False,True
12,GP,M,15,U,LE3,T,4,4,HEALTH,services,...,3,1,3,5,2,14,14,14,False,True
13,GP,M,15,U,GT3,T,4,3,TEACHER,other,...,3,1,2,3,2,10,10,11,False,True
14,GP,M,15,U,GT3,A,2,2,OTHER,other,...,2,1,1,3,0,14,16,16,False,True
15,GP,F,16,U,GT3,T,4,4,HEALTH,other,...,4,1,2,2,4,14,14,14,True,True
16,GP,F,16,U,GT3,T,4,4,SERVICES,services,...,3,1,2,2,6,13,14,14,True,True
17,GP,F,16,U,GT3,T,3,3,OTHER,other,...,2,1,1,4,4,8,10,10,True,True
18,GP,M,17,U,GT3,T,3,2,SERVICES,services,...,5,2,4,5,16,6,5,5,True,True
19,GP,M,16,U,LE3,T,4,3,HEALTH,other,...,3,1,3,5,4,8,10,10,True,True
20,GP,M,15,U,GT3,T,4,3,TEACHER,other,...,1,1,1,1,0,13,14,15,False,True
21,GP,M,15,U,GT3,T,4,4,HEALTH,health,...,2,1,1,5,0,12,15,15,False,True
22,GP,M,16,U,LE3,T,4,2,TEACHER,other,...,1,1,3,5,2,15,15,16,True,True
23,GP,M,16,U,LE3,T,2,2,OTHER,other,...,4,2,4,5,0,13,13,12,True,True
24,GP,F,15,R,GT3,T,2,4,SERVICES,health,...,2,1,1,5,2,10,9,8,False,True
25,GP,F,16,U,GT3,T,2,2,SERVICES,services,...,2,1,3,5,14,6,9,8,True,True
26,GP,M,15,U,GT3,T,2,2,OTHER,other,...,2,1,2,5,2,12,12,11,False,True
27,GP,M,15,U,GT3,T,4,2,HEALTH,services,...,4,2,4,1,4,15,16,15,False,True
28,GP,M,16,U,LE3,A,3,4,SERVICES,other,...,3,1,1,5,4,11,11,11,True,True
29,GP,M,16,U,GT3,T,4,4,TEACHER,teacher,...,5,5,5,5,16,10,12,11,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,AT_HOME,other,...,4,2,4,3,4,10,10,10,True,True
366,MS,M,18,U,LE3,T,4,4,TEACHER,services,...,2,2,2,5,0,13,13,13,True,True
367,MS,F,17,R,GT3,T,1,1,OTHER,services,...,1,1,2,1,0,7,6,0,True,True
368,MS,F,18,U,GT3,T,2,3,AT_HOME,services,...,3,1,2,4,0,11,10,10,True,True
369,MS,F,18,R,GT3,T,4,4,OTHER,teacher,...,2,4,2,5,10,14,12,11,True,True
370,MS,F,19,U,LE3,T,3,2,SERVICES,services,...,2,1,1,3,4,7,7,9,True,True
371,MS,M,18,R,LE3,T,1,2,AT_HOME,services,...,3,2,3,3,3,14,12,12,True,True
372,MS,F,17,U,GT3,T,2,2,OTHER,at_home,...,3,1,1,3,8,13,11,11,True,True
373,MS,F,17,R,GT3,T,1,2,OTHER,other,...,5,1,3,1,14,6,5,5,True,True
374,MS,F,18,R,LE3,T,4,4,OTHER,other,...,4,1,1,1,0,19,18,19,True,True
375,MS,F,18,R,GT3,T,1,1,OTHER,other,...,2,1,2,4,2,8,8,10,True,True
376,MS,F,20,U,GT3,T,4,2,HEALTH,other,...,3,1,1,3,4,15,14,15,True,True
377,MS,F,18,R,LE3,T,4,4,TEACHER,services,...,3,3,4,2,4,8,9,10,True,True
378,MS,F,18,U,GT3,T,3,3,OTHER,other,...,3,1,2,1,0,15,15,15,True,True
379,MS,F,17,R,GT3,T,3,1,AT_HOME,other,...,4,2,3,1,17,10,10,10,True,True
380,MS,M,18,U,GT3,T,4,4,TEACHER,teacher,...,4,1,4,2,4,15,14,14,True,True
381,MS,M,18,R,GT3,T,2,1,OTHER,other,...,3,1,3,5,5,7,6,7,True,True
382,MS,M,17,U,GT3,T,2,3,OTHER,services,...,3,1,1,3,2,11,11,10,True,True
383,MS,M,19,R,GT3,T,1,1,OTHER,services,...,2,1,3,5,0,6,5,0,True,True
384,MS,M,18,R,GT3,T,4,2,OTHER,other,...,3,4,3,3,14,6,5,5,True,True
385,MS,F,18,R,GT3,T,2,2,AT_HOME,other,...,3,1,3,4,2,10,9,10,True,True
386,MS,F,18,R,GT3,T,4,4,TEACHER,at_home,...,3,2,2,5,7,6,5,6,True,True
387,MS,F,19,R,GT3,T,2,3,SERVICES,other,...,2,1,2,5,0,7,5,0,True,True
388,MS,F,18,U,LE3,T,3,1,TEACHER,services,...,4,1,1,1,0,7,9,8,True,True
389,MS,F,18,U,GT3,T,1,1,OTHER,other,...,1,1,1,5,0,6,5,0,True,True
390,MS,M,20,U,LE3,A,2,2,SERVICES,services,...,4,4,5,4,11,9,9,9,True,True
391,MS,M,17,U,LE3,T,3,1,SERVICES,services,...,5,3,4,2,3,14,16,16,True,True
392,MS,M,21,R,GT3,T,1,1,OTHER,other,...,3,3,3,3,3,10,8,7,True,True
393,MS,M,18,R,LE3,T,3,2,SERVICES,other,...,1,3,4,5,0,11,12,10,True,True
394,MS,M,19,U,LE3,T,1,1,OTHER,at_home,...,3,3,3,5,5,8,9,9,True,True

# step10

In [121]:
for i in df.columns:
    if df[i].dtypes =='int64':
        df[i]=df[i].apply(lambda x:x*10)

In [122]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,ss,legal
0,GP,F,180,U,GT3,A,40,40,AT_HOME,teacher,...,40,10,10,30,60,50,60,60,True,True
1,GP,F,170,U,GT3,T,10,10,AT_HOME,other,...,30,10,10,30,40,50,50,60,True,True
2,GP,F,150,U,LE3,T,10,10,AT_HOME,other,...,20,20,30,30,100,70,80,100,False,True
3,GP,F,150,U,GT3,T,40,20,HEALTH,services,...,20,10,10,50,20,150,140,150,False,True
4,GP,F,160,U,GT3,T,30,30,OTHER,other,...,20,10,20,50,40,60,100,100,True,True
5,GP,M,160,U,LE3,T,40,30,SERVICES,other,...,20,10,20,50,100,150,150,150,True,True
6,GP,M,160,U,LE3,T,20,20,OTHER,other,...,40,10,10,30,0,120,120,110,True,True
7,GP,F,170,U,GT3,A,40,40,OTHER,teacher,...,40,10,10,10,60,60,50,60,True,True
8,GP,M,150,U,LE3,A,30,20,SERVICES,other,...,20,10,10,10,0,160,180,190,False,True
9,GP,M,150,U,GT3,T,30,40,OTHER,other,...,10,10,10,50,0,140,150,150,False,True
10,GP,F,150,U,GT3,T,40,40,TEACHER,health,...,30,10,20,20,0,100,80,90,False,True
11,GP,F,150,U,GT3,T,20,10,SERVICES,other,...,20,10,10,40,40,100,120,120,False,True
12,GP,M,150,U,LE3,T,40,40,HEALTH,services,...,30,10,30,50,20,140,140,140,False,True
13,GP,M,150,U,GT3,T,40,30,TEACHER,other,...,30,10,20,30,20,100,100,110,False,True
14,GP,M,150,U,GT3,A,20,20,OTHER,other,...,20,10,10,30,0,140,160,160,False,True
15,GP,F,160,U,GT3,T,40,40,HEALTH,other,...,40,10,20,20,40,140,140,140,True,True
16,GP,F,160,U,GT3,T,40,40,SERVICES,services,...,30,10,20,20,60,130,140,140,True,True
17,GP,F,160,U,GT3,T,30,30,OTHER,other,...,20,10,10,40,40,80,100,100,True,True
18,GP,M,170,U,GT3,T,30,20,SERVICES,services,...,50,20,40,50,160,60,50,50,True,True
19,GP,M,160,U,LE3,T,40,30,HEALTH,other,...,30,10,30,50,40,80,100,100,True,True
20,GP,M,150,U,GT3,T,40,30,TEACHER,other,...,10,10,10,10,0,130,140,150,False,True
21,GP,M,150,U,GT3,T,40,40,HEALTH,health,...,20,10,10,50,0,120,150,150,False,True
22,GP,M,160,U,LE3,T,40,20,TEACHER,other,...,10,10,30,50,20,150,150,160,True,True
23,GP,M,160,U,LE3,T,20,20,OTHER,other,...,40,20,40,50,0,130,130,120,True,True
24,GP,F,150,R,GT3,T,20,40,SERVICES,health,...,20,10,10,50,20,100,90,80,False,True
25,GP,F,160,U,GT3,T,20,20,SERVICES,services,...,20,10,30,50,140,60,90,80,True,True
26,GP,M,150,U,GT3,T,20,20,OTHER,other,...,20,10,20,50,20,120,120,110,False,True
27,GP,M,150,U,GT3,T,40,20,HEALTH,services,...,40,20,40,10,40,150,160,150,False,True
28,GP,M,160,U,LE3,A,30,40,SERVICES,other,...,30,10,10,50,40,110,110,110,True,True
29,GP,M,160,U,GT3,T,40,40,TEACHER,teacher,...,50,50,50,50,160,100,120,110,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,180,R,GT3,T,10,30,AT_HOME,other,...,40,20,40,30,40,100,100,100,True,True
366,MS,M,180,U,LE3,T,40,40,TEACHER,services,...,20,20,20,50,0,130,130,130,True,True
367,MS,F,170,R,GT3,T,10,10,OTHER,services,...,10,10,20,10,0,70,60,0,True,True
368,MS,F,180,U,GT3,T,20,30,AT_HOME,services,...,30,10,20,40,0,110,100,100,True,True
369,MS,F,180,R,GT3,T,40,40,OTHER,teacher,...,20,40,20,50,100,140,120,110,True,True
370,MS,F,190,U,LE3,T,30,20,SERVICES,services,...,20,10,10,30,40,70,70,90,True,True
371,MS,M,180,R,LE3,T,10,20,AT_HOME,services,...,30,20,30,30,30,140,120,120,True,True
372,MS,F,170,U,GT3,T,20,20,OTHER,at_home,...,30,10,10,30,80,130,110,110,True,True
373,MS,F,170,R,GT3,T,10,20,OTHER,other,...,50,10,30,10,140,60,50,50,True,True
374,MS,F,180,R,LE3,T,40,40,OTHER,other,...,40,10,10,10,0,190,180,190,True,True
375,MS,F,180,R,GT3,T,10,10,OTHER,other,...,20,10,20,40,20,80,80,100,True,True
376,MS,F,200,U,GT3,T,40,20,HEALTH,other,...,30,10,10,30,40,150,140,150,True,True
377,MS,F,180,R,LE3,T,40,40,TEACHER,services,...,30,30,40,20,40,80,90,100,True,True
378,MS,F,180,U,GT3,T,30,30,OTHER,other,...,30,10,20,10,0,150,150,150,True,True
379,MS,F,170,R,GT3,T,30,10,AT_HOME,other,...,40,20,30,10,170,100,100,100,True,True
380,MS,M,180,U,GT3,T,40,40,TEACHER,teacher,...,40,10,40,20,40,150,140,140,True,True
381,MS,M,180,R,GT3,T,20,10,OTHER,other,...,30,10,30,50,50,70,60,70,True,True
382,MS,M,170,U,GT3,T,20,30,OTHER,services,...,30,10,10,30,20,110,110,100,True,True
383,MS,M,190,R,GT3,T,10,10,OTHER,services,...,20,10,30,50,0,60,50,0,True,True
384,MS,M,180,R,GT3,T,40,20,OTHER,other,...,30,40,30,30,140,60,50,50,True,True
385,MS,F,180,R,GT3,T,20,20,AT_HOME,other,...,30,10,30,40,20,100,90,100,True,True
386,MS,F,180,R,GT3,T,40,40,TEACHER,at_home,...,30,20,20,50,70,60,50,60,True,True
387,MS,F,190,R,GT3,T,20,30,SERVICES,other,...,20,10,20,50,0,70,50,0,True,True
388,MS,F,180,U,LE3,T,30,10,TEACHER,services,...,40,10,10,10,0,70,90,80,True,True
389,MS,F,180,U,GT3,T,10,10,OTHER,other,...,10,10,10,50,0,60,50,0,True,True
390,MS,M,200,U,LE3,A,20,20,SERVICES,services,...,40,40,50,40,110,90,90,90,True,True
391,MS,M,170,U,LE3,T,30,10,SERVICES,services,...,50,30,40,20,30,140,160,160,True,True
392,MS,M,210,R,GT3,T,10,10,OTHER,other,...,30,30,30,30,30,100,80,70,True,True
393,MS,M,180,R,LE3,T,30,20,SERVICES,other,...,10,30,40,50,0,110,120,100,True,True
394,MS,M,190,U,LE3,T,10,10,OTHER,at_home,...,30,30,30,50,50,80,90,90,True,True