In [2]:
import pandas as pd
import numpy as np

In [3]:
cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")
cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")

# 4

In [5]:
cars1 = cars1.loc[:,'mpg':'car']
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

# 5

In [7]:
cars1.shape

(198, 9)

In [8]:
cars2.shape

(200, 9)

# 6

In [11]:
cars = cars1.append(cars2)

In [12]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe
183,36.0,4,107,75,2205,14.5,82,3,honda accord
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla
185,38.0,4,91,67,1965,15.0,82,3,honda civic
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto)
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx
188,25.0,6,181,110,2945,16.4,82,1,buick century limited
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion
191,22.0,6,232,112,2835,14.7,82,1,ford granada l
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

# 7

In [14]:
nr_owners = np.random.randint(15000,high=73001,size=398,dtype='l')

In [15]:
nr_owners

array([31213, 58596, 16057, 66057, 56619, 34832, 56229, 23224, 33494,
       44571, 51058, 27368, 54400, 61733, 53723, 38924, 66642, 49714,
       55739, 55790, 38359, 23992, 27035, 69366, 24819, 69398, 68297,
       69941, 48237, 67846, 69659, 52020, 66881, 26157, 43973, 61952,
       43413, 44894, 58693, 15609, 22237, 50993, 53907, 30501, 68599,
       57262, 53113, 65171, 16798, 53755, 36352, 22373, 36015, 37504,
       62915, 24717, 68881, 49348, 26529, 49935, 65336, 26004, 26460,
       66395, 16974, 18490, 45677, 58056, 17328, 35510, 70556, 62848,
       39998, 60270, 57012, 20034, 21607, 67613, 17737, 67550, 46902,
       36368, 70607, 33751, 22756, 49385, 52138, 29797, 66323, 27339,
       65269, 44052, 64849, 56798, 59682, 26447, 34134, 25846, 54398,
       34600, 17223, 15712, 37989, 64764, 42685, 38287, 48019, 42339,
       30977, 34266, 52448, 61474, 67664, 29263, 48262, 25202, 18975,
       68351, 27290, 16798, 59075, 61643, 71387, 62912, 37593, 67125,
       52410, 54269, 53929, 22698, 39010, 21198, 70882, 26720, 33860,
       40727, 32057, 34976, 53475, 22765, 37184, 33450, 71649, 58881,
       53948, 49520, 36283, 65219, 37115, 49167, 67692, 20415, 15457,
       43737, 58781, 66341, 60568, 60467, 33415, 21838, 59911, 18786,
       27748, 44515, 59178, 71652, 31977, 70631, 56977, 40591, 58526,
       38727, 35185, 38317, 59497, 45142, 60678, 48104, 63375, 39218,
       63340, 52915, 37533, 31175, 31697, 47135, 25996, 68321, 28462,
       32802, 53998, 22325, 54949, 30270, 43331, 15453, 50161, 22767,
       16861, 41664, 43272, 20403, 58389, 17817, 55721, 63676, 68779,
       40395, 27962, 44134, 16929, 60684, 39860, 37286, 49697, 70874,
       55661, 21365, 23677, 51199, 24048, 52796, 32079, 71354, 57069,
       36763, 56460, 50232, 28356, 66510, 69151, 24354, 44381, 67714,
       71355, 62292, 18292, 54321, 15943, 30290, 53867, 54392, 35764,
       45742, 72387, 64902, 43708, 29530, 18562, 23370, 59406, 24241,
       35298, 49081, 22848, 19026, 40051, 58506, 34631, 18912, 58870,
       56175, 58084, 66481, 47389, 55204, 36849, 21363, 16086, 42560,
       26234, 34798, 41688, 29494, 71405, 57854, 66538, 20515, 35532,
       30021, 22053, 36549, 57827, 32118, 47610, 43944, 71454, 64936,
       33501, 56867, 22627, 24253, 51282, 59847, 15914, 64949, 62783,
       16372, 41721, 44063, 21243, 33297, 34159, 27389, 26748, 68776,
       21641, 19463, 55842, 41839, 31109, 63882, 64755, 36703, 48271,
       41695, 18581, 44661, 71570, 64509, 70834, 17177, 41303, 40113,
       59768, 23680, 32750, 70078, 41907, 71108, 71457, 72192, 70223,
       65166, 60913, 40682, 72915, 43777, 21466, 61805, 39218, 65008,
       34793, 66711, 38902, 53394, 52980, 40445, 59992, 56828, 32788,
       56996, 71509, 50022, 32192, 22881, 47014, 52112, 44370, 27291,
       54553, 15925, 61332, 45151, 68439, 21652, 58517, 57119, 72782,
       25769, 48412, 23763, 61390, 49526, 69632, 69524, 68718, 54743,
       64629, 67158, 60520, 25605, 28087, 33279, 42557, 71446, 27462,
       19296, 72936, 58024, 47988, 43981, 31293, 52554, 27057, 18513,
       60575, 16862])

In [16]:
cars['aa'] = nr_owners

In [17]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,aa
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,31213
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,58596
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,16057
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,66057
4,17.0,8,302,140,3449,10.5,70,1,ford torino,56619
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,34832
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,56229
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,23224
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,33494
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,44571
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,51058
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,27368
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,54400
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),61733
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,53723
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,38924
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,66642
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,49714
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,55739
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,55790
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,38359
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,23992
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,27035
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,69366
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,24819
25,10.0,8,360,215,4615,14.0,70,1,ford f250,69398
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,68297
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,69941
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,48237
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,67846
...,...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,72782
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,25769
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,48412
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se,23763
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,61390
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,49526
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl,69632
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,69524
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,68718
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,54743
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,64629
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,67158
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,60520
183,36.0,4,107,75,2205,14.5,82,3,honda accord,25605
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla,28087
185,38.0,4,91,67,1965,15.0,82,3,honda civic,33279
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),42557
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,71446
188,25.0,6,181,110,2945,16.4,82,1,buick century limited,27462
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),19296
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,72936
191,22.0,6,232,112,2835,14.7,82,1,ford granada l,58024
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,47988
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,43981
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,31293
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,52554
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,27057
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,18513
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,60575
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,16862