In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('lianjiabj.csv')

In [3]:
df

,标题,面积,楼型,建筑年份,挂牌时间,上次交易,地区,区域,小区,单价,总价,户型,楼层,总楼层,关注人数,带看,朝向,装修
0,北京西城月坛99年南北通透大两居，双阳台，采光无遮挡,77.70,板楼,1999年,2018-08-21,2013-09-09,西城,月坛,月坛北街25号院,126127.0,980.0,2室1厅,底层,6,9390,37,南 北,精装
1,靠近地铁8号线，小区中间位置，中间楼层，已经满五年,124.08,板楼,2006年,2018-10-31,2006-10-17,昌平,回龙观,和谐家园一区,43521.0,540.0,3室2厅,低楼层,6,1942,72,南 北,简装
2,太阳宫 南北大三居 高层安静看花园 免征个税 有钥匙,148.66,板楼,2003年,2018-06-22,2009-08-31,朝阳,三元桥,UHN国际村,86103.0,1280.0,3室2厅,顶层,28,2104,37,南 北,精装
3,新龙城 南北通透三居室 中高楼层 精装空闲,113.19,板塔结合,2007年,2018-09-26,2011-01-30,昌平,回龙观,新龙城,52920.0,599.0,3室1厅,中楼层,20,17605,39,南 北,精装
4,朝阳区东坝金隅景和园南向精装修两居室,87.00,板楼,2011年,2018-06-24,2012-09-25,朝阳,东坝,金隅景和园,48046.0,418.0,2室1厅,低楼层,21,203,56,南,精装
5,满五年唯一税费少，带10平米面积，低楼层，采光无遮,49.01,板楼,1983年,2018-10-30,2003-03-19,丰台,北大地,北大街南里,62131.0,304.5,2室1厅,底层,6,358,41,南 北,简装
6,曙光花园西南两居，满五年唯一住房，公房，大厅主卧南,98.28,塔楼,2000年,2018-11-10,2001-03-22,海淀,四季青,曙光花园,95442.0,938.0,2室1厅,中楼层,17,37,28,南 西,精装
7,潘家园小区两居室 满五年 无个税 有电梯,66.09,板楼,1990年,2018-11-16,2010-03-04,朝阳,潘家园,潘家园小区,52959.0,350.0,2室1厅,顶层,18,192,27,南 西 北,简装
8,南北通透 前后观花园 满五年 家庭名下有一套住房,194.93,板楼,2008年,2018-03-21,2010-04-22,朝阳,豆各庄,富力又一城B区,47197.0,920.0,4室2厅,中楼层,22,363,22,南 北,精装
9,三面采光三居室 没有户口没有尾款 只有诚意,103.27,板楼,2000年,2018-04-27,2010-05-01,昌平,回龙观,云趣园一区,43769.0,452.0,3室2厅,高楼层,6,473,53,南 北,简装
10,房子满五年唯一 小区环境优雅 总价低三居室,91.00,塔楼,1999年,2018-04-28,2003-02-27,海淀,万寿路,万寿路甲15号院五区,95385.0,868.0,3室1厅,底层,18,531,14,东 南 北,简装
11,南北通透两居室，市长楼业主诚心出售。,126.55,板楼,1990年,2018-06-29,2009-03-11,东城,东花市,东花市北里中区,75860.0,960.0,2室1厅,低楼层,6,483,46,南 北,精装
12,复兴路乙6号院经典小两居一层带院,52.50,塔楼,1986年,2018-09-04,2002-04-28,海淀,军博,复兴路乙6号院,86667.0,455.0,2室1厅,底层,16,809,41,西南,简装
13,马家堡，10年商品房，人车分流，全明格局，精装婚房,96.86,板塔结合,2010年,2018-09-05,2011-03-21,丰台,大红门,上海建筑,68966.0,668.0,3室1厅,顶层,15,136,33,东南,精装
14,地铁龙泽站1千米+精装修+中间层两居室+满五年,80.16,板楼,1996年,2018-10-10,2013-10-25,昌平,回龙观,龙华园,49776.0,399.0,2室1厅,低楼层,6,124,64,南 北,精装
15,玺萌公馆 两居室南北通透 满五年唯一,118.83,板楼,2009年,2018-10-16,2011-12-22,丰台,草桥,玺萌公馆,79947.0,950.0,2室2厅,中楼层,6,182,39,南 北,毛坯
16,龙禧一正规三居室！中间楼层和位置！业主诚心出售！,105.00,板楼,2002年,2018-10-18,2003-09-23,昌平,回龙观,龙禧苑一区,45715.0,480.0,3室1厅,中楼层,7,75,40,南 北,简装
17,奥林匹克花园一期 满五年唯一164平三居室 一层带花园,163.79,板楼,2003年,2017-11-17,2004-06-15,朝阳,东坝,奥林匹克花园一期,85476.0,1400.0,3室3厅,底层,6,1472,31,南 北,精装
18,平层大四居，满五年唯一，东边户，明厨明卫；,208.73,板塔结合,2008年,2018-11-06,2010-06-30,朝阳,朝青,天鹅湾北区,71864.0,1500.0,4室2厅,低楼层,23,72,23,南 北,精装
19,大井东里南北通透两居室，卧室面积大，采光好，随时签,62.81,板楼,1995年,2018-08-16,2013-07-01,丰台,岳各庄,大井东里,45853.0,288.0,2室1厅,顶层,6,77,21,南 北,简装
20,天乐园安静不临街，精装两居，业主诚意出售可随时签约,86.38,板楼,2004年,2017-07-19,2009-02-24,朝阳,奥林匹克公园,天乐园,71313.0,616.0,2室1厅,中楼层,17,738,25,南,精装
21,一层带花园 三面采光 满五年 小区中间位置,119.85,板楼,1996年,2017-12-27,2001-01-04,昌平,北七家,西湖新村,34877.0,418.0,3室2厅,底层,7,295,24,南 西 北,简装
22,全天采光好 无遮挡 满五年唯一住房 诚意出售,156.23,塔楼,2004年,2018-03-19,2006-06-05,朝阳,大望路,珠江帝景,81931.0,1280.0,3室2厅,低楼层,26,360,29,西南,精装
23,本房是满五唯一的，南北通透的三居室，观景房,117.78,板塔结合,2007年,2018-05-16,2009-05-12,房山,长阳,碧桂园小区C区,29632.0,349.0,3室2厅,中楼层,16,120,22,南 北,简装
24,明源南里 已购公房 南北通透 无遮挡 采光好,55.67,板楼,1984年,2018-05-29,1998-03-03,房山,良乡,明源南里,34489.0,192.0,2室1厅,高楼层,6,1105,20,南 北,简装
25,融域嘉园 高层三居，双卧朝南，有车位,157.02,板塔结合,2007年,2018-06-24,2009-06-03,朝阳,奥林匹克公园,融域嘉园,87887.0,1380.0,3室2厅,顶层,15,1294,22,南 北,精装
26,南北通透全明格局，采光充足 视野好无遮挡 有钥匙,219.72,板楼,2000年,2018-06-25,2010-04-27,朝阳,望京,华鼎世家一期,65356.0,1436.0,3室2厅,中楼层,20,134,28,南 北,精装
27,南北通透2居室 满五年唯一 双卫 层高3米,103.64,板楼,2007年,2018-07-17,2009-02-10,丰台,玉泉营,优筑,65612.0,680.0,2室2厅,中楼层,17,61,23,南 北,精装
28,文慧园10号院 2室1厅 560万,64.30,板楼,1980年,2018-08-04,2012-08-24,海淀,新街口,文慧园10号院,87092.0,560.0,2室1厅,中楼层,6,135,24,南 北,其他
29,北四环，南北通透两居室，一直自住，满五唯一，户型好,67.34,板楼,1998年,2018-08-24,2001-06-18,朝阳,南沙滩,龙欣苑小区,74102.0,499.0,2室1厅,底层,6,46,23,南 北,精装
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,卧室双朝南 光照充足 无噪音 诚心出售,104.30,板塔结合,2009年,2018-03-24,2012-05-11,通州,通州北苑,天时名苑,46501.0,485.0,2室2厅,中楼层,29,72,7,西南,精装
1471,火星园 户型方正明厨明卫 精装两居室 视野棒,94.55,板楼,2011年,2018-05-02,2012-10-22,朝阳,太阳宫,火星园,114226.0,1080.0,2室1厅,中楼层,24,61,25,东 南 北,精装
1472,晨月园正规大一居 东南向不临街 有钥匙 随时看房,68.24,塔楼,2007年,2018-05-05,2012-06-12,海淀,世纪城,晨月园,95253.0,650.0,1室1厅,低楼层,17,41,1,东南,简装
1473,大望路 易构空间 北向开间 视野好,50.34,塔楼,2004年,2018-05-07,2005-08-18,朝阳,大望路,易构空间,69528.0,350.0,1室0厅,高楼层,28,110,3,北,精装
1474,南北通透两居室，高楼层，满五唯一，带大阳台,91.54,板楼,2002年,2018-05-10,2010-12-24,朝阳,常营,柏林爱乐一期,62268.0,570.0,2室2厅,高楼层,11,84,28,南 北,精装
1475,满五唯一 新龙城户型中排位【1】 可接受换房时效,99.26,板楼,2007年,2018-05-13,2009-12-28,昌平,回龙观,新龙城,49366.0,490.0,2室1厅,底层,11,165,28,南 北,精装
1476,富力城B区全南向三居室，看房方便,137.09,板塔结合,2004年,2018-05-19,2012-12-12,朝阳,双井,富力城B区,90963.0,1247.0,3室1厅,低楼层,18,123,22,南,精装
1477,东花市南北通透两居 业主自住随时签约 诚心售,105.16,板楼,1995年,2018-05-20,2003-11-27,东城,东花市,东花市北里中区,78928.0,830.0,2室1厅,顶层,5,164,20,南 北,精装
1478,翠成馨园 南北通透两居 商品房,101.21,板楼,2004年,2018-06-02,2011-12-20,朝阳,垡头,翠成馨园,50885.0,515.0,2室1厅,顶层,6,32,0,南 北,简装
1479,全南向温馨业主自住二层两居室。,93.06,板楼,2000年,2018-06-05,2001-02-28,昌平,回龙观,风雅园三区,45670.0,425.0,2室1厅,低楼层,6,41,27,南,简装
1480,满五唯一 南北通透两居室 刚需选择,70.25,板楼,1998年,2018-06-14,2004-11-08,昌平,立水桥,佳运园一期,50534.0,355.0,2室1厅,底层,6,358,20,南 北,简装
1481,两室两卫双阳台，南向，弧形阳台，全天阳光充足,120.36,塔楼,2002年,2018-06-15,2009-01-04,朝阳,酒仙桥,星城国际,59821.0,720.0,2室1厅,低楼层,26,65,2,南,精装
1482,无遮挡次顶层大两居，视野好无遮挡！,81.97,塔楼,2009年,2018-06-16,2016-08-16,朝阳,潘家园,弘善家园,51849.0,425.0,2室1厅,高楼层,28,112,27,东 北,简装
1483,泰中花园，满五年精装，纯南大一居，落地窗大阳台,81.69,板塔结合,2012年,2018-06-17,2013-04-25,大兴,大兴开发区,泰中花园,40397.0,330.0,1室1厅,中楼层,21,108,4,南,精装
1484,长阳 满五唯一 户型方正 客厅使用面积35.8㎡ 全明格局,92.54,板塔结合,2006年,2018-06-19,2008-10-16,房山,长阳,碧桂园小区C区,30582.0,283.0,2室1厅,低楼层,16,363,27,南 西 北,精装
1485,满五年且家庭名下一套住房 精装修 地暖 拎包入住,89.48,板楼,2012年,2018-06-23,2012-07-03,昌平,北七家,望都新地二期,43027.0,385.0,2室1厅,高楼层,6,61,29,南 北,精装
1486,世纪星城三期不临街不把边！满五唯一！无抵押！随时看,99.14,板楼,2009年,2018-06-24,2012-08-07,通州,通州北苑,世纪星城三期,52048.0,516.0,2室1厅,高楼层,18,79,20,南 北,精装
1487,华纺一居室，满五年，家庭名下一套房，有钥匙,54.66,板塔结合,2006年,2018-07-01,2012-09-19,朝阳,朝青,华纺易城,74644.0,408.0,1室1厅,低楼层,18,40,4,北,简装
1488,怡景园东西向三居室，高层，视野采光好。,197.73,塔楼,2003年,2018-07-06,2007-11-28,朝阳,朝阳门外,怡景园,65747.0,1300.0,3室2厅,高楼层,12,52,28,东 西,精装
1489,电梯房 高楼层 采光好 满五唯一,57.68,板塔结合,2003年,2018-07-08,2005-01-27,丰台,西红门,西宏苑,43863.0,253.0,1室1厅,高楼层,11,139,4,东南,简装
1490,03年低密度小区板楼带电梯 人车分流 上浮式花园7800平,122.44,板塔结合,2003年,2018-07-10,2006-01-16,朝阳,亚运村,阳光新干线,73424.0,899.0,3室2厅,中楼层,16,100,23,东南,简装
1491,户型方正 双卧朝南 满5年 业主唯一住房,88.31,板楼,2000年,2018-07-15,2002-10-21,朝阳,奥林匹克公园,畅清园,68849.0,608.0,2室1厅,底层,7,80,22,南,精装
1492,靠谱出售沙河民园小区满五唯一南北通透看房方便,74.68,板楼,1998年,2018-07-21,2009-01-05,昌平,沙河,民园小区,38297.0,286.0,2室2厅,中楼层,5,113,25,南 北,精装
1493,天通西苑一区 2室1厅 450万,100.91,塔楼,2001年,2018-07-24,2003-08-18,昌平,天通苑,天通西苑一区,44595.0,450.0,2室1厅,中楼层,15,89,5,东南,其他
1494,宋家庄 商品房 前后花园 适合小中老居住,78.99,板楼,2005年,2018-07-28,2012-09-21,丰台,刘家窑,鑫兆雅园北区,70896.0,560.0,2室1厅,低楼层,6,87,25,南 北,精装
1495,低密度板楼 视野开阔 五年唯一 全天沐浴阳光,144.15,板塔结合,2009年,2018-07-29,2010-09-02,西城,广安门,丽水莲花,99896.0,1440.0,3室1厅,低楼层,26,65,21,南 北,精装
1496,后现代城 低总价 全明户型 业主诚意出售,46.39,板塔结合,2004年,2018-07-31,2008-07-08,朝阳,大望路,后现代城,75448.0,350.0,1室0厅,中楼层,18,139,1,北,精装
1497,商品房+南北通透+满五年+无个税+中间层+精装修,84.99,板楼,2000年,2018-08-03,2009-12-22,昌平,回龙观,龙兴园北区,45771.0,389.0,2室2厅,高楼层,6,76,23,南 北,精装
1498,珠江逸景 西向 小两居 朝小区里边,86.78,板楼,2009年,2018-08-03,2011-06-21,通州,马驹桥,珠江逸景,31114.0,270.0,2室1厅,中楼层,14,60,24,西,精装
1499,西城德胜门田字格三居室全明格局中间层水电央产价可谈,79.70,板楼,1984年,2018-08-03,1997-07-18,西城,德胜门,德胜里一区,148056.0,1180.0,3室1厅,中楼层,5,43,26,南 北,精装

In [30]:
#1
df1 = df.挂牌时间.head()
df1

0    2018-08-21
1    2018-10-31
2    2018-06-22
3    2018-09-26
4    2018-06-24
Name: 挂牌时间, dtype: object

In [31]:
#2
df2=df.groupby('小区').count()
df2['标题']

小区
CBD传奇         1
CLASS         1
DBC加州小镇       1
DBC加州小镇C区     1
SOHO现代城       1
UHN国际村        4
gogo新世代       1
一幅画卷          1
七贤村           1
万寿路甲15号院五区    1
万寿路西街12号院     1
万年花城三期        2
万年花城二期        8
万年花城五期        1
万年花城四期        3
万年花城回迁        1
万恒家园          1
万泉新新家园        1
万科中粮假日风景      1
万科四季花城        1
万科城市花园        5
万科星园          5
万科紫苑          4
万科青青家园        2
万象新天二区        2
万象新天四区        2
三义东里          3
三嘉信苑          1
三庙街           1
三环新城6号院       1
             ..
黄平路8号院        1
黑山东街          1
鼎立水岸家园        1
龙乡中区          1
龙兴园北区         1
龙华园           7
龙博苑一区         1
龙博苑三区         3
龙博苑二区         3
龙回苑           1
龙城花园S区        1
龙旗广场          1
龙欣苑小区         1
龙泽苑东区         2
龙泽苑西区         5
龙湖蔚澜香醍        1
龙禧苑一区         2
龙翔路小区         2
龙腾苑二区         1
龙腾苑六区         2
龙腾苑四区         1
龙跃苑一区         1
龙跃苑三区         1
龙跃苑东二区        1
龙跃苑东四区        1
龙锦苑东一区        1
龙锦苑东二区        2
龙锦苑五区         1
龙锦苑六区         2
龙锦苑四区         1
Name: 标题, Length: 1001, dtype: int64

In [33]:
#3
df3 = df.sort_values('挂牌时间').head(5)
df3

,标题,面积,楼型,建筑年份,挂牌时间,上次交易,地区,区域,小区,单价,总价,户型,楼层,总楼层,关注人数,带看,朝向,装修
811,角门东里两居，格局好，楼层好，业主诚心卖,62.65,塔楼,1995年,2016-08-17,2009-04-02,丰台,角门,角门东里,60655.0,380.0,2室1厅,高楼层,19,7491,22,东南,精装
1460,方华苑 东向一居室 带阳台 满五年 随时看,64.38,塔楼,1998年,2016-08-24,2011-05-04,朝阳,华威桥,方华苑,57472.0,370.0,1室1厅,低楼层,22,814,4,东,简装
979,世纪东方城 3室2厅 810万,133.87,塔楼,2004年,2016-09-21,2006-04-06,朝阳,欢乐谷,世纪东方城,60507.0,810.0,3室2厅,高楼层,21,136,3,东南,精装
585,南三环 草桥玺萌鹏苑 西南向三居室,137.52,塔楼,2003年,2016-11-04,2004-11-15,丰台,草桥,玺萌丽苑,55992.0,770.0,3室1厅,底层,24,431,6,西南,简装
1461,北纬南向一层复式小2居 满五唯一 业主诚售！,83.83,板塔结合,2008年,2016-12-25,2010-05-11,朝阳,望京,北纬40度一期,71455.0,599.0,2室1厅,底层,29,398,29,南,简装

In [34]:
#4
df4 = df.groupby('地区').count()
df4['标题']

地区
东城        38
丰台       288
亦庄开发区     10
大兴        87
房山        51
昌平       173
朝阳       459
海淀       147
石景山       39
西城        79
通州        66
门头沟       27
顺义        36
Name: 标题, dtype: int64

In [35]:
#5
df5=df.groupby(['地区','单价']).count()
df5['标题']

地区  单价
东城  61542.0     1
    61923.0     1
    65970.0     1
    68830.0     1
    70127.0     1
    70708.0     1
    74592.0     1
    75000.0     1
    75860.0     1
    76444.0     1
    77187.0     1
    78403.0     1
    78928.0     1
    80530.0     1
    81870.0     1
    82811.0     1
    86911.0     1
    87844.0     1
    87945.0     1
    88461.0     1
    89286.0     1
    90072.0     1
    92714.0     1
    102607.0    1
    102816.0    1
    103953.0    1
    105521.0    1
    105977.0    1
    108145.0    1
    112508.0    1
               ..
顺义  36471.0     1
    36516.0     1
    37260.0     1
    37388.0     1
    37594.0     1
    38222.0     1
    38488.0     1
    38801.0     1
    38990.0     1
    39450.0     1
    39461.0     1
    39571.0     1
    40010.0     1
    40190.0     1
    40616.0     1
    40713.0     1
    41141.0     1
    42336.0     1
    42742.0     1
    42803.0     1
    44291.0     1
    45441.0     1
    45805.0     1
    46529.0     1
    48216.0     1
    49296.0     1
    49497.0     1
    50796.0     1
    53784.0     1
    54869.0     1
Name: 标题, Length: 1486, dtype: int64

In [37]:
#6
df6=df.describe()
df6

,面积,单价,总价,总楼层,关注人数,带看
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,100.252633,63700.144667,644.151867,14.485333,206.092667,18.511333
std,41.355357,22099.407445,399.339760,8.334832,847.333315,13.516151
min,33.540000,18528.000000,183.000000,1.000000,0.000000,0.000000
25%,70.190000,48083.750000,388.000000,6.000000,43.000000,8.000000
50%,90.550000,58987.500000,530.000000,14.000000,86.000000,16.000000
75%,119.957500,75079.250000,756.000000,21.000000,165.000000,25.000000
max,349.130000,149834.000000,4200.000000,42.000000,17605.000000,117.000000

In [38]:
#7
df7=df.sort_values('面积',ascending=False)
df7.head(10)

,标题,面积,楼型,建筑年份,挂牌时间,上次交易,地区,区域,小区,单价,总价,户型,楼层,总楼层,关注人数,带看,朝向,装修
1095,四环内海淀区正规大五居，满五年唯一，楼龄新,349.13,塔楼,2000年,2017-12-28,2012-11-26,海淀,五棵松,今日家园,45829.0,1600.0,5室3厅,高楼层,18,164,6,西南,简装
1125,红玺台东户高层观景房几乎全新拎包即住,300.84,板楼,2011年,2018-03-19,2012-11-08,朝阳,太阳宫,红玺台,139610.0,4200.0,4室2厅,高楼层,24,223,1,南 北,精装
1314,中粮祥云北区 平层别墅 契税票已满两年 精装拎包入住,300.72,板楼,2013年,2018-05-29,2015-06-09,顺义,后沙峪,中粮祥云国际生活区,54869.0,1650.0,3室2厅,中楼层,15,57,10,东 南 北,精装
1110,清华大学北门、庭院别墅（边户大户型，大花园）、,290.20,暂无数据,2007年,2018-07-21,2012-11-02,海淀,五道口,褐石,113715.0,3300.0,4室3厅,底层,5,108,10,南 北,精装
1093,银枫家园 精装复式4居室 带露台 俯瞰望京公园,276.25,塔楼,2002年,2017-09-29,2007-05-08,朝阳,大山子,银枫家园,41629.0,1150.0,4室2厅,顶层,25,384,8,西南 西北,简装
345,看房随时 随时签约 价格有大惊喜 高楼层 西南无遮挡,272.94,塔楼,2003年,2018-08-14,2011-03-12,朝阳,工体,光彩国际公寓,80604.0,2200.0,4室2厅,高楼层,28,76,13,西南,精装
1106,西斯莱公馆五居室，采光好，看房方便,268.29,板塔结合,2012年,2018-06-13,2016-03-01,大兴,高米店南,新里.西斯莱公馆,44728.0,1200.0,5室2厅,顶层,24,164,8,西南,精装
1124,慧谷根园 5室2厅 1880万,266.01,暂无数据,2002年,2018-02-25,2004-04-20,朝阳,望京,慧谷根园,70675.0,1880.0,5室2厅,底层,3,18,35,南 北,其他
357,上河村三区 平层大三居 免个税 带产权车位,263.18,板楼,2006年,2018-01-21,2009-02-18,海淀,世纪城,鲁艺上河村三区,129190.0,3400.0,3室2厅,低楼层,11,108,3,南 北,精装
1375,高层边户观景朝阳公园！11年建成+市政地暖+2梯2户！,257.14,板楼,2011年,2018-02-03,2012-12-06,朝阳,燕莎,华远九都汇,89446.0,2300.0,4室2厅,高楼层,23,121,3,东 南 北,精装

In [39]:
#8
df8=df.sort_values('挂牌时间').head()
df8.head(10)

,标题,面积,楼型,建筑年份,挂牌时间,上次交易,地区,区域,小区,单价,总价,户型,楼层,总楼层,关注人数,带看,朝向,装修
811,角门东里两居，格局好，楼层好，业主诚心卖,62.65,塔楼,1995年,2016-08-17,2009-04-02,丰台,角门,角门东里,60655.0,380.0,2室1厅,高楼层,19,7491,22,东南,精装
1460,方华苑 东向一居室 带阳台 满五年 随时看,64.38,塔楼,1998年,2016-08-24,2011-05-04,朝阳,华威桥,方华苑,57472.0,370.0,1室1厅,低楼层,22,814,4,东,简装
979,世纪东方城 3室2厅 810万,133.87,塔楼,2004年,2016-09-21,2006-04-06,朝阳,欢乐谷,世纪东方城,60507.0,810.0,3室2厅,高楼层,21,136,3,东南,精装
585,南三环 草桥玺萌鹏苑 西南向三居室,137.52,塔楼,2003年,2016-11-04,2004-11-15,丰台,草桥,玺萌丽苑,55992.0,770.0,3室1厅,底层,24,431,6,西南,简装
1461,北纬南向一层复式小2居 满五唯一 业主诚售！,83.83,板塔结合,2008年,2016-12-25,2010-05-11,朝阳,望京,北纬40度一期,71455.0,599.0,2室1厅,底层,29,398,29,南,简装

In [44]:
#9
df9=df.groupby(['地区','带看']).count()
df9

        标题  面积  楼型  建筑年份  挂牌时间  上次交易  区域  小区  单价  总价  户型  楼层  总楼层  关注人数  朝向  \
地区  带看
东城  5    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    6    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    7    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    8    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    9    3   3   3     3     3     3   3   3   3   3   3   3    3     3   3
    11   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    12   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    14   3   3   3     3     3     3   3   3   3   3   3   3    3     3   3
    16   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    18   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    19   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    20   4   4   4     4     4     4   4   4   4   4   4   4    4     4   4
    21   3   3   3     3     3     3   3   3   3   3   3   3    3     3   3
    22   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    23   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    24   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    27   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    28   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    29   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    39   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    44   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    46   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    51   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    58   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    61   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
丰台  0    4   4   4     4     4     4   4   4   4   4   4   4    4     4   4
    1    8   8   8     8     8     8   8   8   8   8   8   8    8     8   8
    2    5   5   5     5     5     5   5   5   5   5   5   5    5     5   5
    3    7   7   7     7     7     7   7   7   7   7   7   7    7     7   7
    4    8   8   8     8     8     8   8   8   8   8   8   8    8     8   8
...     ..  ..  ..   ...   ...   ...  ..  ..  ..  ..  ..  ..  ...   ...  ..
门头沟 22   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    24   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    25   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    27   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    37   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    38   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    42   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    49   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    87   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
顺义  0    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    1    5   5   5     5     5     5   5   5   5   5   5   5    5     5   5
    3    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    5    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    6    2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    7    1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    8    3   3   3     3     3     3   3   3   3   3   3   3    3     3   3
    9    3   3   3     3     3     3   3   3   3   3   3   3    3     3   3
    10   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    11   3   3   3     3     3     3   3   3   3   3   3   3    3     3   3
    12   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    13   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    14   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    15   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    16   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    18   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    22   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    26   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    31   2   2   2     2     2     2   2   2   2   2   2   2    2     2   2
    36   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1
    39   1   1   1     1     1     1   1   1   1   1   1   1    1     1   1

        装修
地区  带看
东城  5    1
    6    1
    7    1
    8    1
    9    3
    11   2
    12   1
    14   3
    16   1
    18   1
    19   2
    20   4
    21   3
    22   2
    23   1
    24   1
    27   2
    28   1
    29   1
    39   1
    44   1
    46   1
    51   1
    58   1
    61   1
丰台  0    4
    1    8
    2    5
    3    7
    4    8
...     ..
门头沟 22   2
    24   1
    25   1
    27   1
    37   1
    38   1
    42   1
    49   1
    87   1
顺义  0    1
    1    5
    3    1
    5    1
    6    2
    7    1
    8    3
    9    3
    10   2
    11   3
    12   1
    13   2
    14   1
    15   1
    16   1
    18   1
    22   2
    26   1
    31   2
    36   1
    39   1

[444 rows x 16 columns]

In [45]:
#10
df.columns
#没有停车位

Index(['标题', '面积', '楼型', '建筑年份', '挂牌时间', '上次交易', '地区', '区域', '小区', '单价', '总价',
       '户型', '楼层', '总楼层', '关注人数', '带看', '朝向', '装修'],
      dtype='object')

In [50]:
#11
df11=df.groupby('地区').count()
df11['标题']

地区
东城        38
丰台       288
亦庄开发区     10
大兴        87
房山        51
昌平       173
朝阳       459
海淀       147
石景山       39
西城        79
通州        66
门头沟       27
顺义        36
Name: 标题, dtype: int64

In [51]:
#12
df.groupby('')

,标题,面积,楼型,建筑年份,挂牌时间,上次交易,区域,小区,单价,总价,户型,楼层,总楼层,关注人数,带看,朝向,装修
地区,,,,,,,,,,,,,,,,,
东城,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38
丰台,288,288,288,288,288,288,288,288,288,288,288,288,288,288,288,288,288
亦庄开发区,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
大兴,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87
房山,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51
昌平,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173
朝阳,459,459,459,459,459,459,459,459,459,459,459,459,459,459,459,459,459
海淀,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147
石景山,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39
西城,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79
通州,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66
门头沟,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27
顺义,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36